### ISSUE TITLE
Mech Bay 3D Model Loading Errors

### ISSUE THREAD

**Issue by LarkinOmega** [Sheep-y/BattleTech_Turbine#4]
Mech 3D models sometimes will not load until another mech in the bay is selected, then both models are loaded until another mech is selected.

Bug Occurs on the first load of the 3D model, sometimes. It only affects the 3D background model, not the mech icons in the selection pane. Once the model is loaded in memory, for as long as it is memory, it responds normally. It is a minor bug at best, just an annoyance.

[Log_Turbine.txt](https://github.com/Sheep-y/BattleTech_Turbine/files/2264370/Log_Turbine.txt)
[BTModLoader.log](https://github.com/Sheep-y/BattleTech_Turbine/files/2264371/BTModLoader.log)

**Comment by Sheep-y** [comment]
I can't reproduce the issue in campaign (and skirmish mech bay is always empty). The game also keeps its own log as BATTLETECH\BattleTech_Data\output_log.txt which may have more information, can you try to make the bug happens and then attach that log?

**Comment by LarkinOmega** [comment]
[output_log.txt](https://github.com/Sheep-y/BattleTech_Turbine/files/2265703/output_log.txt)

That is from my latest session, the error did appear but it was a rather long session.

[output_log.txt](https://github.com/Sheep-y/BattleTech_Turbine/files/2265714/output_log.txt)

That one was loading into campaign, purposefully causing the bug, then exiting the game. In this instance it happened on the third Mech that I tried to load. The background stays in the black fade transition, and then when it loads the next mech, the two of them load together.

If you cannot recreate the issue, perhaps it's hardware related. Here are my system specs as reported through steam. https://pastebin.com/aDw2d5bH

**Comment by Sheep-y** [comment]
Thanks for the logs.  I do see a MechBay error in the longer session but not the shorter one.  I'll try harder to reproduce and see if I can fix the error in the long one.

**Comment by LarkinOmega** [comment]
After further testing, it is loading the weapons on the 3D model that is causing the black background. I can reliably reproduce the bug by swapping between two of the same mech model, with different fittings. I don't think this will ever be an issue in the Skirmish bay, due to the lack of the 3D background model.

Step to reproduce:
1) Ensure there are two mechs of the same type in the campaign mech bay. Different variants does not matter, just that they use the same 3D Mech Model.
2) Have one selected, then click on the second one. Background should stay in the black transition until a 3rd different mech is selected. On my system it sometimes stays black until a 4th mech is selected.

If you still can't reproduce it, try with the two Jaegermechs, since their arm pods are significantly different.

**Comment by Sheep-y** [comment]
Confirmed and can reproduce. Thanks for the detailed steps!

**Comment by Sheep-y** [comment]
The culprit is `Override_CombatGameConstants_CreateFromSaved`.  Maybe the game is waiting for a data completion message that never come because the loading is bypassed.

**Comment by Sheep-y** [comment]
New version is released that should have fixd the issue.

https://github.com/Sheep-y/BattleTech_Turbine/releases
