### ISSUE TITLE
1.0.5 Cannot load RT save

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/BattleTech_Turbine#5]
outis on rougetech channel report that the following save cannot be loaded on 1.0.5, but is ok on 1.0.4.

[b72bbf44-1a81-47c6-862e-22709d009588.zip](https://github.com/Sheep-y/BattleTech_Turbine/files/2266065/b72bbf44-1a81-47c6-862e-22709d009588.zip)

RT version is v.988 patch3HF2

**Comment by Sheep-y** [comment]
Another save from Tubben. RT v.988 3HF3

[d8f6a63c-d998-41f8-a692-e8798ddb3a68.zip](https://github.com/Sheep-y/BattleTech_Turbine/files/2266789/d8f6a63c-d998-41f8-a692-e8798ddb3a68.zip)

**Comment by CptMoore** [comment]
can you just load those in principle? I thought its more complicated to load saves if your index (cloud save?) is gone.

**Comment by Sheep-y** [comment]
I have decided to give up and disable mechcomponentdef shortcuts. It's not a big save. The new json processing in 1.0.6 is both safer and more than make up for cutting it.
